AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for s3 bucket
Resources:
  LambdaAutoRiaToS3AndRDSDaily:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::062261762656:role/service-role/yelp_reader_lambda-role-ic07vv5u
      FunctionName: auto_ria_to_s3_and_rds_daily
      Code:
        S3Bucket: ts-mybucket-001
        S3Key: auto_ria_src/lambda/auto_ria_to_s3_and_rds_daily.zip
      Runtime: python3.8
      Timeout: 300
      MemorySize: 3008
      Environment:
        Variables:
          DATABASE: riadbgha
          DB_HOST: riadbinstance.cs1ac7ipvtir.eu-central-1.rds.amazonaws.com
          DB_PASSWORD: postgres
          DB_PORT: 5432
          DB_USER: postgres
          S3_BUCKET: ts-mybucket-001
          TABLE: auto_ria_analyzer_daily
      Layers: [ 'arn:aws:lambda:eu-central-1:336392948345:layer:AWSDataWrangler-Python39:1',
                'arn:aws:lambda:eu-central-1:062261762656:layer:psycopg2-python38:1']
  AutoRiaToS3AndRDSDailyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "AutoRia To S3 and RDS Daily Event Rule"
      Name: auto_ria_to_s3_and_rds_daily_rule
      ScheduleExpression: 'cron(50 13 * * ? *)'
      State: "ENABLED"
      Targets:
        - Arn: 'arn:aws:lambda:eu-central-1:062261762656:function:auto_ria_to_s3_and_rds_daily'
          Id: "AutoRiaEventRule"
  PermissionForEventsToInvokeLambdaAutoRiaToS3AndRDSDaily:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: 'auto_ria_to_s3_and_rds_daily'
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "AutoRiaToS3AndRDSDailyEventRule"
          - "Arn"
