AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for s3 bucket
Resources:
  LambdaAutoRiaToS3AndRDSDaily:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::062261762656:role/service-role/yelp_reader_lambda-role-ic07vv5u
      FunctionName: auto_ria_to_s3_and_rds_daily
      Code:
        S3Bucket: ts-mybucket-001
        ZipFile: auto_ria_src/lambda/auto_ria_to_s3_and_rds_daily.zip
      Runtime: python3.9
      Timeout: 300
      MemorySize: 3008
      Environment:
        Variables:
          DATABASE: postgres
          DB_HOST: ria-db-postgres.cs1ac7ipvtir.eu-central-1.rds.amazonaws.com
          DB_PASSWORD: 12345678
          DB_PORT: 5432
          DB_USER: postgres
          S3_BUCKET: ts-mybucket-001
          TABLE: daily_auto_ria
      Layers: [ 'arn:aws:lambda:eu-central-1:336392948345:layer:AWSDataWrangler-Python39:1' ]
