name: DeployStack

on:
  [workflow_dispatch]
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: lambda_ingestion_transfer
        run: |
          zip -r auto_ria_to_s3_and_rds_daily.zip extract_layer load_layer transform_layer lambda_function.py
          aws s3 cp auto_ria_to_s3_and_rds_daily.zip s3://ts-mybucket-001/auto_ria_src/lambda/auto_ria_to_s3_and_rds_daily.zip
      - name: deploy
        run: |
          aws cloudformation deploy --stack-name ghaStack --template-file test.yaml
