name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          python-version: '3.9'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ aws_secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ aws_secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: deploy
        run: |
          zip -j deploy.zip ./yelp_business_to_parquet.py
          aws lambda update-function-code --function-name=lyelp_business_to_parquet --zip-file=fileb://deploy.zip
