name: Lambda_actions

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: deploy
        run: |
          zip -j yelp_business_to_parquet.zip yelp_business_to_parquet.py
          aws s3 cp yelp_business_to_parquet.zip s3://ts-mybucket-001/lambda/yelp_business_to_parquet.zip
          aws s3 cp lambda.yaml s3://ts-mybucket-001/lambda/lambda.yaml
          aws cloudformation deploy --stack-name gha-stack --template-file lambda.yaml --s3-bucket ts-mybucket-001 --s3-prefix lambda --region eu-central-1