name: Pylint

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint ( lambda_ingestion )
      run: |
        pylint lambda_ingestion.py.py
    - name: Analysing the code with pylint ( rds_start )
      run: |
        pylint rds_start.py
    - name: Analysing the code with pylint ( rds_stop )
      run: |
        pylint rds_stop.py
