name: Pylint

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint ( lambda_function )
      run: |
        pylint --fail-under=10.0 lambda_function.py
    - name: Analysing the code with pylint ( processor )
      run: |
        pylint --fail-under=10.0 transform_layer/processor.py
    - name: Analysing the code with pylint ( s3_loader )
      run: |
        pylint --fail-under=10.0 load_layer/s3_loader.py
    - name: Analysing the code with pylint ( rds_loader )
      run: |
        pylint --fail-under=10.0 load_layer/rds_loader.py
    - name: Analysing the code with pylint ( autoria_reader )
      run: |
        pylint --fail-under=10.0 extract_layer/autoria_reader.py
    - name: Analysing the code with pylint ( s3_reader )
      run: |
        pylint --fail-under=10.0 extract_layer/s3_reader.py
        
