name: UpdateRiaStack

on:
  push:
    branches:
      - 'master'

jobs:
  update_ria_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: ingestion_lambda_transfer
        run: |
          aws s3 cp deploy_stack.yml s3://ts-mybucket-001/auto_ria_src/cf_templates/deploy_stack.yml

      - name: ingestion_lambda_transfer
        run: |
          zip -j auto_ria_to_s3_and_rds_daily.zip lambda_ingestion.py
          aws s3 cp auto_ria_to_s3_and_rds_daily.zip s3://ts-mybucket-001/auto_ria_src/lambda/auto_ria_to_s3_and_rds_daily.zip
      - name: rds_start_lambda_transfer
        run: |
          zip -j rds_start.zip rds_start.py
          aws s3 cp rds_start.zip s3://ts-mybucket-001/auto_ria_src/lambda/rds_start.zip
      - name: rds_stop_lambda_transfer
        run: |
          zip -j rds_stop.zip rds_stop.py
          aws s3 cp rds_stop.zip s3://ts-mybucket-001/auto_ria_src/lambda/rds_stop.zip
      - name: update_stack
        run: |
          aws cloudformation update-stack --stack-name ghaStack --template-url s3://ts-mybucket-001/auto_ria_src/cf_templates/deploy_stack.yml
